### ISSUE TITLE
ClassNotFoundException: mk.gdx.firebase.ios.App

### ISSUE THREAD

**Issue by TomGrill** [mk-5/gdx-fireapp#2]
When I run this app: https://github.com/TomGrill/gdx-fireapp-test

I get this exception:

```
IOSApplication 3 Total computed bounds are w=640.0 h=960.0
com.badlogic.gdx.utils.reflect.ReflectionException: Class not found: mk.gdx.firebase.ios.App
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:30)
	at mk.gdx.firebase.PlatformDistributor.<init>(PlatformDistributor.java:90)
	at mk.gdx.firebase.GdxFIRApp.<init>(GdxFIRApp.java:42)
	at mk.gdx.firebase.GdxFIRApp.instance(GdxFIRApp.java:55)
	at de.tomgrill.fireapp.MyGdxGame.create(MyGdxGame.java:23)
	at com.badlogic.gdx.backends.iosmoe.IOSGraphics.glkViewDrawInRect(IOSGraphics.java:228)
	at com.badlogic.gdx.backends.iosmoe.IOSGLKView.drawRect(IOSGLKView.java:76)
	at apple.uikit.c.UIKit.UIApplicationMain(Native Method)
	at de.tomgrill.fireapp.IOSMoeLauncher.main(IOSMoeLauncher.java:24)
Caused by: java.lang.ClassNotFoundException: mk.gdx.firebase.ios.App
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:325)
	at java.lang.Class.forName(Class.java:286)
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:28)
	... 8 more
Caused by: java.lang.ClassNotFoundException: mk.gdx.firebase.ios.App
	at java.lang.Class.classForName(Native Method)
	at java.lang.BootClassLoader.findClass(ClassLoader.java:792)
	at java.lang.BootClassLoader.loadClass(ClassLoader.java:852)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:480)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: Lmk/gdx/firebase/ios/App;
	... 16 more
mk.gdx.firebase.exceptions.PlatformDistributorException: Something wrong with environment
	at mk.gdx.firebase.PlatformDistributor.<init>(PlatformDistributor.java:94)
	at mk.gdx.firebase.GdxFIRApp.<init>(GdxFIRApp.java:42)
	at mk.gdx.firebase.GdxFIRApp.instance(GdxFIRApp.java:55)
	at de.tomgrill.fireapp.MyGdxGame.create(MyGdxGame.java:23)
	at com.badlogic.gdx.backends.iosmoe.IOSGraphics.glkViewDrawInRect(IOSGraphics.java:228)
	at com.badlogic.gdx.backends.iosmoe.IOSGLKView.drawRect(IOSGLKView.java:76)
	at apple.uikit.c.UIKit.UIApplicationMain(Native Method)
	at de.tomgrill.fireapp.IOSMoeLauncher.main(IOSMoeLauncher.java:24)
java.lang.NullPointerException: Attempt to invoke virtual method 'void mk.gdx.firebase.GdxFIRApp.configure()' on a null object reference
	at de.tomgrill.fireapp.MyGdxGame.create(MyGdxGame.java:23)
	at com.badlogic.gdx.backends.iosmoe.IOSGraphics.glkViewDrawInRect(IOSGraphics.java:228)
	at com.badlogic.gdx.backends.iosmoe.IOSGLKView.drawRect(IOSGLKView.java:76)
	at apple.uikit.c.UIKit.UIApplicationMain(Native Method)
	at de.tomgrill.fireapp.IOSMoeLauncher.main(IOSMoeLauncher.java:24)
```

Since the class is there I think it might happen because each class exists twice in the jar:
Image: https://ibb.co/nqyStw

This is the app I am working with to test: Simple gds app.
https://github.com/TomGrill/gdx-fireapp-test

**Comment by TomGrill** [comment]
Ok solved by adding the proguard rules.

**Comment by TomGrill** [comment]
Well adding the proguard rules throws another error. Maybe because of missing bindings which I cannot create. See issue #1

**Comment by TomGrill** [comment]
Ok this was just an issue caused by missing bindings from issue #1
