### ISSUE TITLE
Didn't find class "pl.mk5.gdx.fireapp.android.App" on path: DexPathList

### ISSUE THREAD

**Issue by code4passion** [mk-5/gdx-fireapp#38]
When i try the instructions here i get following error.  Am using following dependencies.

Core 
implementation "pl.mk5.gdx-fireapp:gdx-fireapp-core:2.1.7"

Android
dependencies {
    // your other dependencies..
    compile "pl.mk5.gdx-fireapp:gdx-fireapp-android:1.9.3"

    compile 'com.google.firebase:firebase-core:16.0.0'
    compile 'com.google.firebase:firebase-storage:16.0.1'
    compile 'com.google.firebase:firebase-auth:16.0.1'
    compile 'com.google.firebase:firebase-database:16.0.1'

    // Add this if you need google authorization
    compile 'com.google.android.gms:play-services-auth:16.0.0'
}
apply plugin: 'com.google.gms.google-services'

```
Caused by: java.lang.ClassNotFoundException: pl.mk5.gdx.fireapp.android.App
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:28)
        at pl.mk5.gdx.fireapp.PlatformDistributor.<init>(PlatformDistributor.java:77) 
        at pl.mk5.gdx.fireapp.GdxFIRApp.<init>(GdxFIRApp.java:38) 
        at pl.mk5.gdx.fireapp.Api.instance(Api.java:61) 
        at pl.mk5.gdx.fireapp.GdxFIRApp.instance(GdxFIRApp.java:42) 
        at pl.mk5.gdx.fireapp.GdxFIRApp.inst(GdxFIRApp.java:49) 
        at com.mindedges.citydefender.MainGame.signIn(MainGame.java:61) 
        at com.mindedges.citydefender.MainGame.create(MainGame.java:41) 
        at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:310) 
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1555) 
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.mk5.gdx.fireapp.android.App" on path: DexPathList[[zip file "/data/app/com.mindedges.citydefender-fcEIQB7UY80V6R4iICAf3A==/base.apk"],nativeLibraryDirectories=[/data/app/com.mindedges.citydefender-fcEIQB7UY80V6R4iICAf3A==/lib/arm, /data/app/com.mindedges.citydefender-fcEIQB7UY80V6R4iICAf3A==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by mk-5** [comment]
Hello @code4passion ,

mhmm you are using two different versions. 2.1.7, and 1.9.3 there are not compatible. Using the same version for `core`, and `android` should help .

But, I've got your point -> the android WIKI page is outdated. I will update it. Thanks for reporting!

**Comment by mk-5** [comment]
@code4passion is that works for you?
